development:
  facebook_key: 'facebook_key'
  facebook_secret: 'facebook_secret'

staging:
  facebook_key: 'facebook_key'
  facebook_secret: 'facebook_secret'

production:
  facebook_key: 'facebook_key'
  facebook_secret: 'facebook_secret'


